# basic options
title: Guangbo Blog
author: guangbo
email: ygbuestc@gmail.com
description: my blog
twitter_username: guangboyu
github_username: guangboyu

# Build settings
markdown: kramdown
theme: minima
